#!/usr/bin/env -S sage -python

# Other features we could add:
# * Random object
# * Another database connection (other than devmirror)

# TODO: Add json and tsv language support to downloads

from lmfdb.cmdline_search import main

if __name__ == "__main__":
    main()
