

# This file was *autogenerated* from the file check_correctness.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
from collections import defaultdict
sys.path.append("../..") 
from lmfdb import db

counts_filenames = ["counts23_0_1728.txt", "counts.txt"]

counts  = defaultdict(int)

def is_int(s):
    try:
        int(s)
        return True
    except ValueError:
        return False
    
for filename in counts_filenames:
    with open(filename, "r") as file:
        for line in file:
            line = line.strip()
            line = line.replace(" ", "")
            if not line: 
                continue
            tokens = line.split(",")
            
            if all(is_int(token) for token in tokens) and len(tokens)>_sage_const_1 :
                counts[int(tokens[_sage_const_0 ])] += int(tokens[_sage_const_1 ])
                
lmfdb_counts = db.av_fq_isog.stats.column_counts(["g", "q"])

for key in sorted(counts.keys()):
    assert lmfdb_counts[(_sage_const_1 , key)] == counts[key]

print("SUCCESS: we just verified that the number of labels in our output matches the lmfdb data.")
    

