
import unittest

from flask import request

from lmfdb.tests import LmfdbTest
from lmfdb.utils import to_dict, get_search_type
from lmfdb.utils.search_boxes import SearchArray, SearchButton

# A harmless sentinel: if it survives unescaped, the quotes would terminate
# the surrounding attribute and add a "data-injected" attribute
INJECTION = "x'y\" data-injected=sentinel"


class SearchButtonTest(unittest.TestCase):
    """
    Unit tests for the HTML generated by search buttons.
    """

    def test_plain_value(self):
        button = SearchButton("Dimensions", "Dimension table")
        html = button._input({})
        assert "name='search_type' value='Dimensions'" in html

    def test_value_attribute_escaped(self):
        # A quote-bearing value must not terminate the single-quoted value
        # attribute of the button and introduce additional attributes
        button = SearchButton(INJECTION, "Search again")
        html = button._input({})
        assert INJECTION not in html
        assert "data-injected='sentinel'" not in html
        assert "value='x&#39;y&#34; data-injected=sentinel'" in html


class GenericSearchTypesTest(unittest.TestCase):
    """
    Unit tests for the search buttons produced by the generic SearchArray.
    """

    def test_list_mode(self):
        types = SearchArray().search_types({"search_type": "List"})
        assert types[0] == ("", "Search again")

    def test_unknown_mode_not_preserved(self):
        # An unknown search_type (treated as an ordinary list search by
        # SearchWrapper) is rendered as list mode, not echoed back
        types = SearchArray().search_types({"search_type": INJECTION})
        assert types[0] == ("", "Search again")

    def test_diagram_mode_preserved(self):
        types = SearchArray().search_types({"search_type": "Diagram", "has_diagram": True})
        assert types[0] == ("Diagram", "Search again")
        # the Diagram button is not offered again in diagram mode
        assert all(v != "Diagram" for v, d in types[1:])
        # Diagram is only preserved on pages where diagram search is available
        types = SearchArray().search_types({"search_type": "Diagram"})
        assert types[0] == ("", "Search again")


class GetSearchTypeTest(LmfdbTest):
    """
    Direct tests for the get_search_type helper.
    """

    def test_precedence(self):
        assert get_search_type({"search_type": "Traces", "hst": "List"}) == "Traces"
        assert get_search_type({"hst": "Family"}) == "Family"
        assert get_search_type({}) == ""
        assert get_search_type({}, default="Motive") == "Motive"

    def test_single_value(self):
        with self.app.test_request_context("/?search_type=Traces&hst=Dimensions"):
            assert get_search_type(to_dict(request.args)) == "Traces"

    def test_explicit_empty_overrides_hst(self):
        # to_dict drops the explicitly submitted empty search_type, but it
        # must still take precedence over a stale hst
        with self.app.test_request_context("/?search_type=&hst=Family"):
            info = to_dict(request.args)
            assert "search_type" not in info
            assert get_search_type(info, default="Motive") == ""

    def test_repeated_values(self):
        # When falling back on the raw request, the last value wins.  Note
        # that to_dict records the *first* value of a repeated argument, so
        # a route wanting last-value-wins must consult the request itself
        with self.app.test_request_context("/?search_type=Subgroups&search_type=List"):
            assert get_search_type({}) == "List"
        with self.app.test_request_context("/?search_type=Subgroups&search_type=&hst=Subgroups"):
            assert get_search_type({}) == ""

    def test_normalized_info_wins(self):
        # A search_type already recorded in info (e.g. normalized by a route
        # or wrapper) is not undone by the raw request
        with self.app.test_request_context("/?search_type=Subgroups&search_type=List"):
            assert get_search_type({"search_type": "Diagram"}) == "Diagram"
            assert get_search_type({"search_type": ""}) == ""


class SearchTypeReflectionTest(LmfdbTest):
    """
    Tests that a request-supplied search_type is never reflected unescaped
    into the results page.
    """

    def test_unknown_search_type_not_reflected(self):
        # Number fields use the generic SearchArray, and SearchWrapper
        # treats the unknown mode as an ordinary list search
        page = self.tc.get(
            "/NumberField/", query_string={"degree": "2", "search_type": INJECTION}
        ).get_data(as_text=True)
        assert "Number field search results" in page
        # no unescaped copy of the sentinel anywhere in the page
        assert INJECTION not in page
        assert "data-injected='sentinel'" not in page
        assert 'data-injected="sentinel"' not in page
        # the Search again button reverts to ordinary list mode
        assert "name='search_type' value=''" in page

    def test_diagram_search_type_preserved(self):
        # Diagram results pages still submit search_type=Diagram
        page = self.tc.get(
            "/NumberField/", query_string={"degree": "2", "search_type": "Diagram"}
        ).get_data(as_text=True)
        assert "name='search_type' value='Diagram'" in page
